# Generated by Django 4.0.3 on 2022-03-26 06:05

import django.core.validators
from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=40, validators=[django.core.validators.MinLengthValidator(3), validators.custom_validators.validator_only_letters_numbers]),
        ),
    ]
