# Generated by Django 4.0.3 on 2022-03-31 06:54

from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images', validators=[validators.custom_validators.ValidatorMaxSizeInMB(10)]),
        ),
    ]
