# Generated by Django 4.0.3 on 2022-04-26 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
